version: "3.9"
services:
  worker:
    build: .
    environment:
      STRING_SESSION: $STRING_SESSION
      API_ID: $API_ID
      API_HASH: $API_HASH
      MONGO_DB_URI: $MONGO_DB_URI
      LOG_GROUP_ID: $LOG_GROUP_ID
      BOT_TOKEN: $BOT_TOKEN
      MUSIC_BOT_NAME: $MUSIC_BOT_NAME
      OWNER_ID: $OWNER_ID
      SUDO_USERS_ID: $SUDO_USER_ID
      GBAN_LOG_GROUP_ID: $GBAN_LOG_GROUP_ID
      WELCOME_DELAY_KICK_SEC: $WELCOME_DELAY_KICK_SEC
      ARQ_API_URL: $ARQ_API_URL
      MESSAGE_DUMP_CHAT: $MESSAGE_DUMP_CHAT
      ARQ_API_KEY: $ARQ_API_KEY
      LOG_MENTIONS: $LOG_MENTIONS
      USERBOT_PREFIX: $USERBOT_PREFIX
      RSS_DELAY: $RSS_DELAY
      PM_PERMIT: $PM_PERMIT
